async function generatePDF(config) {
    const { pageFormat, pages, size, sizeUnit } = config;

    window.logToUI('Starting PDF generation...');
    window.updateProgress(30, 'Creating PDF...');
    window.logToUI(`Page format: ${pageFormat.toUpperCase()}`);

    // Access jsPDF from global window object (loaded via CDN)
    const { jsPDF } = window.jspdf;

    // Create PDF with specified format
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: pageFormat
    });

    if (size) {
        // Generate PDF to reach target size
        const targetBytes = convertToBytes(size, sizeUnit);
        window.logToUI(`Target size: ${size} ${sizeUnit} (${targetBytes} bytes)`);
        await generatePDFBySize(doc, pageFormat, targetBytes);
    } else if (pages) {
        // Generate PDF with specific number of pages
        window.logToUI(`Pages: ${pages}`);
        generatePDFByPages(doc, pageFormat, pages);
    } else {
        throw new Error('Either pages or size must be specified');
    }

    window.updateProgress(90, 'Finalizing PDF...');

    // Convert to blob
    const pdfBlob = doc.output('blob');

    window.updateProgress(100, 'Complete!');
    window.logToUI(`PDF generated: ${pdfBlob.size} bytes (${(pdfBlob.size / 1024).toFixed(2)} KB)`);
    setTimeout(() => window.hideProgress(), 2000);

    return pdfBlob;
}

function generatePDFByPages(doc, pageFormat, pageCount) {
    for (let i = 0; i < pageCount; i++) {
        if (i > 0) {
            doc.addPage(pageFormat);
        }

        // Add content to page
        addPageContent(doc, i + 1, pageCount);
    }
}

async function generatePDFBySize(doc, pageFormat, targetBytes) {
    let pageNumber = 1;
    let currentBlob = doc.output('blob');

    // Keep adding pages until we reach or exceed target size
    while (currentBlob.size < targetBytes && pageNumber < 1000) {
        if (pageNumber > 1) {
            doc.addPage(pageFormat);
        }

        // Add content with more text to increase size
        addPageContent(doc, pageNumber, '?', true);

        pageNumber++;
        currentBlob = doc.output('blob');
    }

    // If still not enough, add images or repetitive content
    if (currentBlob.size < targetBytes) {
        doc.addPage(pageFormat);
        addPaddingContent(doc, targetBytes - currentBlob.size);
    }
}

function addPageContent(doc, pageNumber, totalPages, verbose = false) {
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // Title
    doc.setFontSize(24);
    doc.setFont(undefined, 'bold');
    doc.text(`Page ${pageNumber}`, pageWidth / 2, 20, { align: 'center' });

    if (totalPages !== '?') {
        doc.setFontSize(12);
        doc.setFont(undefined, 'normal');
        doc.text(`of ${totalPages}`, pageWidth / 2, 28, { align: 'center' });
    }

    // Add some sample content
    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');

    const sampleText = verbose ? getLongSampleText() : getShortSampleText();
    const lines = doc.splitTextToSize(sampleText, pageWidth - 40);
    doc.text(lines, 20, 45);

    // Add footer
    doc.setFontSize(9);
    doc.setTextColor(128);
    doc.text(`Generated by File Generator`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    doc.setTextColor(0);
}

function addPaddingContent(doc, additionalBytes) {
    // Add repetitive text to increase file size
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(6);

    let text = '';
    const paddingText = 'Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt. ';
    const estimatedCharsNeeded = additionalBytes * 3; // More aggressive estimate

    for (let i = 0; i < estimatedCharsNeeded / paddingText.length; i++) {
        text += paddingText;
    }

    const lines = doc.splitTextToSize(text, pageWidth - 40);

    // Add text across multiple pages if needed
    let y = 20;
    let currentPage = 0;
    const lineHeight = 3;

    for (let i = 0; i < lines.length; i++) {
        if (y > pageHeight - 20) {
            doc.addPage();
            y = 20;
        }
        doc.text(lines[i], 20, y);
        y += lineHeight;
    }
}

function getShortSampleText() {
    return `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

This is a sample PDF document generated with custom specifications. You can configure the page format, number of pages, or target file size.`;
}

function getLongSampleText() {
    return `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.

Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.

At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi.

This is a sample PDF document generated with custom specifications. You can configure the page format, number of pages, or target file size. The generator will automatically adjust the content to meet your requirements.`;
}

function convertToBytes(size, unit) {
    if (unit === 'KB') {
        return size * 1024;
    } else if (unit === 'MB') {
        return size * 1024 * 1024;
    }
    return size;
}
